### ISSUE TITLE
`eliminate` does not return unique HalfSpaces and HyperPlanes

### ISSUE THREAD

**Issue by hdavid16** [JuliaPolyhedra/CDDLib.jl#76] opened 2022-05-18 03:12 UTC
I noticed that doing FM elimination using Polyhedra and CDDLib on a polyhedron may generate an object with duplicate HalfSpaces. Is this the expected behavior of CDDLib? It would be nice to be able to remove duplicates as this could speed up plotting projections on 2D or 3D space. Maybe its just an issue of cdd.

**Comment by blegat** [comment] 2022-06-10 09:35
Closing as duplicate of https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/307

**Closed by blegat** 2022-06-10 09:35 UTC
